<a href="https://colab.research.google.com/github/shanksghub/FootballStats/blob/master/Dec%20Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import matplotlib
from matplotlib import pyplot as plt
import numpy as np
from sklearn.tree import DecisionTreeRegressor as dtr
from sklearn import tree
from sklearn.model_selection import GridSearchCV, train_test_split

In [0]:
url = 'https://raw.githubusercontent.com/shanksghub/FootballStats/master/FootballStats.csv'

df1 = pd.read_csv(url)

In [0]:
df1.describe()
df1 = df1.drop(["position","appearances","blocks","fouls","goals conceded","headed clearances","clearances","saves","punches","yellow cards","red cards","offsides","clean sheets"],axis=1)

In [0]:
df1["goals"].fillna(df1["goals"].mean(), inplace=True)

In [16]:
df1

,name,goals,tackles,passes,assists,shots,hit woordwork,crosses
0,Sergio Agüero,17,16,538.0,6,84,5,7
1,Aymeric Laporte,2,30,2313.0,1,0,0,6
2,Mohamed Salah,17,13,739.0,7,87,1,49
3,Pierre-Emerick Aubameyang,15,19,518.0,4,63,3,26
4,Harry Kane,14,7,446.0,4,77,1,9
5,Eden Hazard,12,9,1273.0,10,67,1,75
6,Sadio Mané,12,30,789.0,9,8,2,0
7,Raheem Sterling,12,22,920.0,46,3,58,14
8,Alexandre Lacazette,10,28,551.0,5,49,1,19
9,Aleksandar Mitrovic,10,18,744.0,2,93,3,5
10,Anthony Martial,9,7,569.0,2,30,0,31
11,Roberto Firmino,9,21,1018.0,4,57,1,6
12,Raúl Jiménez,9,22,725.0,5,81,20,16
13,Joshua King,8,17,529.0,3,47,0,30
14,Richarlison,10,31,560.0,1,55,1,18
15,Paul Pogba,11,28,1423.0,8,79,1,22
16,Son Heung-Min,11,18,5.0,508,21,17,2
17,Gylfi Sigurdsson,9,41,663.0,3,63,3,23
18,Alisson,0,0,731.0,0,0,0,0
19,Ederson,0,0,702.0,1,0,0,0
20,Kepa Arrizabalaga,0,0,748.0,0,0,0,0
21,Hugo Lloris,0,0,721.0,0,0,0,0
22,Martin Dubravka,0,0,741.0,0,0,0,0
23,Neil Etheridge,0,0,791.0,0,0,0,0
24,Ben Foster,0,0,826.0,0,0,0,0
25,Kasper Schmeichel,0,0,740.0,0,0,0,0
26,David De Gea,0,0,666.0,0,0,0,0
27,Rui Patrício,0,0,532.0,0,0,0,0
28,James Tarkowski,3,42,753.0,0,0,1,3
29,Sol Bamba,4,69,520.0,1,0,2,1
30,Steve Cook,1,31,1222.0,1,0,0,11
31,Nathan Aké,3,37,1187.0,0,0,1,1
32,Lucas Digne,3,49,958.0,3,0,2,197
33,Steve Cook,1,31,1222.0,1,0,0,11
34,Jamaal Lascelles,0,25,770.0,1,0,1,150
35,Craig Cathcart,3,40,930.0,0,0,3,3
36,Virgil van Dijk,1,2115,1.0,0,3,0,7
37,Jannik Vestergaard,0,35,NaN,691,0,0,1
38,Fabián Balbuena,1,33,633.0,0,1,1,2
39,Mamadou Sakho,0,25,1282.0,0,0,0,0
40,Denis Odoi,0,37,1153.0,1,0,0,10
41,Lewis Dunk,2,32,989.0,0,0,0,1
42,Nemanja Matic,1,40,1574.0,0,10,0,9
43,David Silva,6,19,1352.0,4,40,0,61
44,Jean Michael Seri,1,40,1463.0,2,16,1,99
45,Rúben Neves,3,55,1297.0,2,56,0,24

In [17]:
df1["goals"] = df1["goals"].apply(np.log) 
y = df1["goals"]
df1 = df1.drop("goals",axis=1)
df1

,name,tackles,passes,assists,shots,hit woordwork,crosses
0,Sergio Agüero,16,538.0,6,84,5,7
1,Aymeric Laporte,30,2313.0,1,0,0,6
2,Mohamed Salah,13,739.0,7,87,1,49
3,Pierre-Emerick Aubameyang,19,518.0,4,63,3,26
4,Harry Kane,7,446.0,4,77,1,9
5,Eden Hazard,9,1273.0,10,67,1,75
6,Sadio Mané,30,789.0,9,8,2,0
7,Raheem Sterling,22,920.0,46,3,58,14
8,Alexandre Lacazette,28,551.0,5,49,1,19
9,Aleksandar Mitrovic,18,744.0,2,93,3,5
10,Anthony Martial,7,569.0,2,30,0,31
11,Roberto Firmino,21,1018.0,4,57,1,6
12,Raúl Jiménez,22,725.0,5,81,20,16
13,Joshua King,17,529.0,3,47,0,30
14,Richarlison,31,560.0,1,55,1,18
15,Paul Pogba,28,1423.0,8,79,1,22
16,Son Heung-Min,18,5.0,508,21,17,2
17,Gylfi Sigurdsson,41,663.0,3,63,3,23
18,Alisson,0,731.0,0,0,0,0
19,Ederson,0,702.0,1,0,0,0
20,Kepa Arrizabalaga,0,748.0,0,0,0,0
21,Hugo Lloris,0,721.0,0,0,0,0
22,Martin Dubravka,0,741.0,0,0,0,0
23,Neil Etheridge,0,791.0,0,0,0,0
24,Ben Foster,0,826.0,0,0,0,0
25,Kasper Schmeichel,0,740.0,0,0,0,0
26,David De Gea,0,666.0,0,0,0,0
27,Rui Patrício,0,532.0,0,0,0,0
28,James Tarkowski,42,753.0,0,0,1,3
29,Sol Bamba,69,520.0,1,0,2,1
30,Steve Cook,31,1222.0,1,0,0,11
31,Nathan Aké,37,1187.0,0,0,1,1
32,Lucas Digne,49,958.0,3,0,2,197
33,Steve Cook,31,1222.0,1,0,0,11
34,Jamaal Lascelles,25,770.0,1,0,1,150
35,Craig Cathcart,40,930.0,0,0,3,3
36,Virgil van Dijk,2115,1.0,0,3,0,7
37,Jannik Vestergaard,35,NaN,691,0,0,1
38,Fabián Balbuena,33,633.0,0,1,1,2
39,Mamadou Sakho,25,1282.0,0,0,0,0
40,Denis Odoi,37,1153.0,1,0,0,10
41,Lewis Dunk,32,989.0,0,0,0,1
42,Nemanja Matic,40,1574.0,0,10,0,9
43,David Silva,19,1352.0,4,40,0,61
44,Jean Michael Seri,40,1463.0,2,16,1,99
45,Rúben Neves,55,1297.0,2,56,0,24

In [0]:
x_train,x_test,y_train,y_test = train_test_split(df1,y,test_size = 0.2)

In [0]:
regressor = dtr(random_state=0)

In [24]:
y_pred = regressor.fit(x_train,y_train)
y_pred

ValueError: ignored